### PR TITLE
PRD initial draft

### PR DESCRIPTION
**Pull request by gagansk**
The PR contains the initial draft of the Product Requirement Document.

### CODE REVIEW

**Comment by msdisme** [comment]
I think I am on a hold till you tell me to do this, should the PR be closed?

**Comment by msdisme** [comment]
@gagansk I think I am still on hold for this, is that correct?  If not, may I close?

**Comment by gagansk** [comment]
Please refer this document for the PRD => https://docs.google.com/document/d/1Rlhs7eoaXrBYOw_mKUn53RuqoP50A7qfm6g7_Mrwan4/edit?usp=sharing

**Comment by gagansk** [comment]
@msdisme The PRD is now ready for review.

**Review by shruthi-raghuraman — COMMENTED** [review]
Made some comments! I know you were going to change the operator metering option anyways

**Comment by shruthi-raghuraman** [comment]
LGTM!

**Pull request merged**
